{"name": "Логин с неверным логином и паролем. :api/auth/login", "status": "passed", "start": 1727338579465, "stop": 1727338580216, "uuid": "16d22989-ecd0-499e-9b44-158960706c11", "historyId": "4ed53cc34b3b2c689e89ca539b766b38", "testCaseId": "4ed53cc34b3b2c689e89ca539b766b38", "fullName": "tests.test_auth_user.TestAuthUser#test_wrong_login_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "Gansalles"}, {"name": "thread", "value": "7584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}